import { jsPDF } from 'jspdf';
import type { PageMetadata } from './types';
import { generateStrokePath } from './stroke-math';
import { renderPageToCanvasAsync } from './canvas-image';

export interface ExportOptions {
  includeInk: boolean;
  includeAI: boolean;
  includeText: boolean;
  format: 'pdf' | 'markdown' | 'html' | 'svg' | 'txt';
}

/**
 * Export page or notebook to Markdown
 */
export function exportToMarkdown(page: PageMetadata, notebookTitle?: string): string {
  let md = `# ${page.title || 'Untitled Note'}\n`;
  if (notebookTitle) md += `*Notebook: ${notebookTitle}*\n`;
  md += `*Template: ${page.pattern} | Theme: ${page.theme}*\n\n`;

  if (page.aiTranscription) {
    md += `## 🤖 Structured Notes & Transcription\n\n`;
    md += page.aiTranscription + '\n\n';
  }

  if (page.textBlocks.length > 0) {
    md += `## 📝 Text Blocks\n\n`;
    page.textBlocks.forEach((tb) => {
      md += `${tb.text}\n\n`;
    });
  }

  if (page.codeBlocks.length > 0) {
    md += `## 💻 Code Blocks\n\n`;
    page.codeBlocks.forEach((cb) => {
      md += `\`\`\`${cb.language}\n${cb.code}\n\`\`\`\n\n`;
    });
  }

  md += `---\n*Generated by OmniNotes Desktop*\n`;
  return md;
}

/**
 * Export page as a standalone SVG vector file
 */
export function exportToSVG(page: PageMetadata): string {
  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${page.width} ${page.height}" width="${page.width}" height="${page.height}">\n`;
  svg += `  <rect width="${page.width}" height="${page.height}" fill="#ffffff"/>\n`;

  // Highlighters
  svg += `  <g style="mix-blend-mode: multiply">\n`;
  page.strokes
    .filter((s) => s.style.penType === 'highlighter')
    .forEach((s) => {
      const d = s.pathData || generateStrokePath(s.points, s.style);
      svg += `    <path d="${d}" fill="${s.style.color}" opacity="0.4"/>\n`;
    });
  svg += `  </g>\n`;

  // Standard strokes
  svg += `  <g>\n`;
  page.strokes
    .filter((s) => s.style.penType !== 'highlighter')
    .forEach((s) => {
      const d = s.pathData || generateStrokePath(s.points, s.style);
      svg += `    <path d="${d}" fill="${s.style.color}" opacity="${s.style.opacity || 1}"/>\n`;
    });
  svg += `  </g>\n`;

  svg += `</svg>`;
  return svg;
}

/**
 * Export page or notebook to PDF using jsPDF with full fidelity ink & PDF background layering
 */
export async function exportToPDF(
  pages: PageMetadata[],
  title: string = 'OmniNotes Notebook'
): Promise<void> {
  if (pages.length === 0) return;

  const firstPage = pages[0];
  const firstW = firstPage.width || 820;
  const firstH = firstPage.height || 1160;

  const doc = new jsPDF({
    orientation: firstW > firstH ? 'landscape' : 'portrait',
    unit: 'pt',
    format: [firstW, firstH],
  });

  for (let i = 0; i < pages.length; i++) {
    const page = pages[i];
    const pageW = page.width || 820;
    const pageH = page.height || 1160;

    if (i > 0) {
      doc.addPage([pageW, pageH], pageW > pageH ? 'landscape' : 'portrait');
    }

    // Render composite page (PDF background + highlighters + user strokes + text blocks)
    const canvas = await renderPageToCanvasAsync(page, {
      maxWidth: Math.round(pageW * 1.5),
      maxHeight: Math.round(pageH * 1.5),
    });

    if (canvas) {
      const imgData = canvas.toDataURL('image/jpeg', 0.90);
      doc.addImage(imgData, 'JPEG', 0, 0, pageW, pageH);
    } else {
      // Fallback text
      doc.setFontSize(16);
      doc.text(page.title || `Page ${i + 1}`, 40, 50);
    }
  }

  doc.save(`${title.toLowerCase().replace(/\s+/g, '-')}.pdf`);
}

/**
 * Trigger file download in browser / desktop
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
