import { jsPDF } from 'jspdf';
import type { PageMetadata } from './types';
import { generateStrokePath } from './stroke-math';

export interface ExportOptions {
  includeInk: boolean;
  includeAI: boolean;
  includeText: boolean;
  format: 'pdf' | 'markdown' | 'html' | 'svg' | 'txt';
}

/**
 * Export page or notebook to Markdown
 */
export function exportToMarkdown(page: PageMetadata, notebookTitle?: string): string {
  let md = `# ${page.title || 'Untitled Note'}\n`;
  if (notebookTitle) md += `*Notebook: ${notebookTitle}*\n`;
  md += `*Template: ${page.pattern} | Theme: ${page.theme}*\n\n`;

  if (page.aiTranscription) {
    md += `## 🤖 Structured Notes & Transcription\n\n`;
    md += page.aiTranscription + '\n\n';
  }

  if (page.textBlocks.length > 0) {
    md += `## 📝 Text Blocks\n\n`;
    page.textBlocks.forEach((tb) => {
      md += `${tb.text}\n\n`;
    });
  }

  if (page.codeBlocks.length > 0) {
    md += `## 💻 Code Blocks\n\n`;
    page.codeBlocks.forEach((cb) => {
      md += `\`\`\`${cb.language}\n${cb.code}\n\`\`\`\n\n`;
    });
  }

  md += `---\n*Generated by OmniNotes Desktop*\n`;
  return md;
}

/**
 * Export page as a standalone SVG vector file
 */
export function exportToSVG(page: PageMetadata): string {
  let svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${page.width} ${page.height}" width="${page.width}" height="${page.height}">\n`;
  svg += `  <rect width="${page.width}" height="${page.height}" fill="#ffffff"/>\n`;

  // Highlighters
  svg += `  <g style="mix-blend-mode: multiply">\n`;
  page.strokes
    .filter((s) => s.style.penType === 'highlighter')
    .forEach((s) => {
      const d = s.pathData || generateStrokePath(s.points, s.style);
      svg += `    <path d="${d}" fill="${s.style.color}" opacity="0.4"/>\n`;
    });
  svg += `  </g>\n`;

  // Standard strokes
  svg += `  <g>\n`;
  page.strokes
    .filter((s) => s.style.penType !== 'highlighter')
    .forEach((s) => {
      const d = s.pathData || generateStrokePath(s.points, s.style);
      svg += `    <path d="${d}" fill="${s.style.color}" opacity="${s.style.opacity || 1}"/>\n`;
    });
  svg += `  </g>\n`;

  svg += `</svg>`;
  return svg;
}

/**
 * Export page or notebook to PDF using jsPDF
 */
export async function exportToPDF(
  pages: PageMetadata[],
  title: string = 'OmniNotes Notebook'
): Promise<void> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pdfWidth = doc.internal.pageSize.getWidth();

  pages.forEach((page, index) => {
    if (index > 0) doc.addPage();

    // Page title header
    doc.setFontSize(18);
    doc.text(page.title || `Page ${index + 1}`, 40, 50);

    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text(`OmniNotes | Template: ${page.pattern} | Strokes: ${page.strokes.length}`, 40, 70);

    // If AI transcription exists, format text into PDF
    if (page.aiTranscription) {
      doc.setFontSize(12);
      doc.setTextColor(30, 30, 30);
      const splitText = doc.splitTextToSize(page.aiTranscription, pdfWidth - 80);
      doc.text(splitText, 40, 100);
    } else {
      doc.setFontSize(11);
      doc.setTextColor(100, 100, 100);
      doc.text(
        `This page contains ${page.strokes.length} handwriting strokes.`,
        40,
        120
      );
    }
  });

  doc.save(`${title.toLowerCase().replace(/\s+/g, '-')}.pdf`);
}

/**
 * Trigger file download in browser / desktop
 */
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
